services:
  app_dev:
    image: node:20-alpine
    container_name: checkin-report-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: [app-net]

networks:
  app-net:
    driver: bridge
