export const ALL_AREAS = [
  'Alabanza',
  'Atmósfera',
  'Velover (Cafeteria)',
  'Bienvenida',
  'Bautismo',
  'Cámaras & Video',
  'Contabilidad (Modulo dar)',
  'Crecer',
  'Dedicaciones',
  'Registro',
  'Desayuno',
  'ED',
  'Equipo Médico',
  'Fin de semana Inolvidable',
  'Get Up',
  'Hombres CDV',
  'Informes',
  'Kids',
  'Logística',
  'Luces',
  'Mantenimiento',
  'Matrimonios',
  'Producción',
  'Recursos',
  'Reps',
  'Sala Verde',
  'Seguridad',
  'Servolución',
  'Sonido',
  'Staff Pastoral (Voluntario)',
  'Líder de Servicio',
  'IDL',
  'Visuales',
  'Grupos pequeños',
  'Comms',
  // agrega/ordena aquí todas las que uses
] as const;

export type AreaName = typeof ALL_AREAS[number];
