export const ALL_AREAS = [
  'Alabanza',
  'Atmósfera',
  'Velover',
  'Bienvenida',
  'Cámaras',
  'Contabilidad',
  'Crecer',
  'Dedicaciones',
  'Registro',
  'Desayuno',
  'ED',
  'Equipo Médico',
  'Fin de semana Inolvidable',
  'Hombres CDV',
  'Informes',
  'Kids',
  'Logística',
  'Luces',
  'Mantenimiento',
  'Matrimonios',
  'Producción',
  'Recursos',
  'Reps',
  'Sala Verde',
  'Seguridad',
  'Servolución',
  'Sonido',
  'Voluntario',
  'Líder de Servicio',
  'IDL',
  'Visuales',
  'Grupos pequeños',
  'Comms',
  // agrega/ordena aquí todas las que uses
] as const;

export type AreaName = typeof ALL_AREAS[number];
