name: Build and Push (Vite + Nginx)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Meta
        id: meta
        run: |
          echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "IMAGE=ghcr.io/ariasbenraq/checkin-report" >> $GITHUB_OUTPUT

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ariasbenraq
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.SHA_SHORT }} \
                       -t ${{ steps.meta.outputs.IMAGE }}:latest .

      - name: Push
        run: |
          docker push ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.SHA_SHORT }}
          docker push ${{ steps.meta.outputs.IMAGE }}:latest
